/**
 * Renders the tokens as CSS custom properties.
 *
 * Light is the `:root` default. Dark applies when the document is marked
 * `data-theme="dark"`, or when the OS prefers dark and the document has not
 * been marked light — which is how "System" works with no JavaScript.
 */

import { darkTheme, lightTheme, type ColorTheme } from "./color.js";
import { radius, shadow, spacing, zIndex } from "./layout.js";
import { duration, easing } from "./motion.js";
import { fontFamily, fontSize, letterSpacing } from "./typography.js";

function kebab(name: string): string {
  return name.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`).replace(/\./g, "-");
}

function colorBlock(theme: ColorTheme): string {
  return Object.entries(theme)
    .map(([name, value]) => `  --color-${kebab(name)}: ${value};`)
    .join("\n");
}

export function renderCss(): string {
  const scalar = [
    ...Object.entries(fontFamily).map(([k, v]) => `  --font-${k}: ${v};`),
    ...Object.entries(fontSize).map(([k, v]) => `  --text-${kebab(k)}: ${String(v)}px;`),
    ...Object.entries(letterSpacing).map(([k, v]) => `  --tracking-${k}: ${v};`),
    ...Object.entries(spacing).map(
      ([k, v]) => `  --space-${k.replace(".", "_")}: ${String(v)}px;`,
    ),
    ...Object.entries(radius).map(([k, v]) => `  --radius-${k}: ${String(v)}px;`),
    ...Object.entries(shadow).map(([k, v]) => `  --shadow-${k}: ${v};`),
    ...Object.entries(duration).map(([k, v]) => `  --duration-${kebab(k)}: ${String(v)}ms;`),
    ...Object.entries(easing).map(([k, v]) => `  --ease-${k}: ${v};`),
    ...Object.entries(zIndex).map(([k, v]) => `  --z-${k}: ${String(v)};`),
  ].join("\n");

  return [
    "/* Generated by @betng/design-tokens. Do not edit; edit src/*.ts. */",
    "",
    ":root {",
    "  color-scheme: light;",
    scalar,
    colorBlock(lightTheme),
    "}",
    "",
    ':root[data-theme="dark"] {',
    "  color-scheme: dark;",
    colorBlock(darkTheme),
    "}",
    "",
    "@media (prefers-color-scheme: dark) {",
    '  :root:not([data-theme="light"]) {',
    "    color-scheme: dark;",
    colorBlock(darkTheme).replace(/^ {2}/gm, "    "),
    "  }",
    "}",
    "",
    "@media (prefers-reduced-motion: reduce) {",
    "  :root {",
    ...Object.keys(duration).map((k) => `    --duration-${kebab(k)}: 0ms;`),
    "  }",
    "}",
    "",
  ].join("\n");
}
