import { ChevronDown, Download, FileClock } from "lucide-react";
import { Dropdown } from "@betng/ui-web";

export interface ExportControlProps {
  /** What the loaded rows are, for the menu label: "this page", "this window". */
  readonly scope: string;
  readonly rowCount: number;
  readonly onExport: () => void;
}

/* Loaded rows are exported here; a full-range export is the platform's job and has no route yet, so it is shown as pending. */
export function ExportControl({ scope, rowCount, onExport }: ExportControlProps): React.JSX.Element {
  return (
    <Dropdown
      label="Export"
      trigger={
        <span className="inline-flex h-8 items-center gap-1.5 rounded-sm border border-border-strong bg-surface px-3 text-sm font-medium text-text-primary hover:bg-surface-hover">
          <Download className="size-3.5" aria-hidden />
          Export
          <ChevronDown className="size-3.5 text-text-muted" aria-hidden />
        </span>
      }
      items={[
        { key: "loaded", label: `CSV of ${scope} (${String(rowCount)} rows)`, icon: <Download />, disabled: rowCount === 0, disabledReason: "Nothing loaded to export", onSelect: onExport },
        { key: "full", label: "Full range (platform-generated)", icon: <FileClock />, disabled: true, disabledReason: "Large exports are generated by the platform. Pending backend: no export route is served yet.", onSelect: () => undefined },
      ]}
    />
  );
}
