/**
 * Plain values only — no zod, no `@zudojs/*`, nothing touching Node — so a
 * browser or React Native bundle can import these constants without
 * pulling in a validation library and `node:crypto`.
 */

export const REQUEST_ID_HEADER = "x-request-id";

export const API_PREFIX = "/api/v1";

export const CURRENCY = "NGN" as const;

export type Currency = typeof CURRENCY;

export const ErrorCodes = Object.freeze({
  VALIDATION_FAILED: "VALIDATION_FAILED",
  NOT_FOUND: "NOT_FOUND",
  METHOD_NOT_ALLOWED: "METHOD_NOT_ALLOWED",
  CONFLICT: "CONFLICT",
  UNAUTHENTICATED: "UNAUTHENTICATED",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  FORBIDDEN: "FORBIDDEN",
  RATE_LIMITED: "RATE_LIMITED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  MARKET_CLOSED: "MARKET_CLOSED",
  ODDS_CHANGED: "ODDS_CHANGED",
  STAKE_LIMITED: "STAKE_LIMITED",
  RISK_REJECTED: "RISK_REJECTED",
  INSUFFICIENT_FUNDS: "INSUFFICIENT_FUNDS",
  INVALID_BET: "INVALID_BET",
  DUPLICATE_SIMULATION: "DUPLICATE_SIMULATION",
  DUPLICATE_SETTLEMENT: "DUPLICATE_SETTLEMENT",
  RESULT_IMMUTABLE: "RESULT_IMMUTABLE",
  SIMULATION_FAILED: "SIMULATION_FAILED",
  SETTLEMENT_FAILED: "SETTLEMENT_FAILED",
  ODDS_UNAVAILABLE: "ODDS_UNAVAILABLE",
  RISK_UNAVAILABLE: "RISK_UNAVAILABLE",
  DATABASE_UNAVAILABLE: "DATABASE_UNAVAILABLE",
  UPSTREAM_UNAVAILABLE: "UPSTREAM_UNAVAILABLE",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  NOT_IMPLEMENTED: "NOT_IMPLEMENTED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
});

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

export function matchChannel(matchId: string): string {
  return `match:${matchId}`;
}

export const MATCH_CHANNEL_PATTERN = /^match:([0-9a-fA-F-]{36})$/;
