export const keys = {
  root: ["admin"] as const,
  overview: ["admin", "overview"] as const,
  health: ["admin", "health"] as const,
  customers: (q: string) => ["admin", "customers", q] as const,
  shops: ["admin", "shops"] as const,
  shop: (id: string) => ["admin", "shop", id] as const,
  cashiers: (shopId: string) => ["admin", "cashiers", shopId] as const,
  allCashiers: ["admin", "cashiers", "all"] as const,
  teams: (leagueId?: string) => ["admin", "teams", leagueId ?? "all"] as const,
  fixtures: (query: object) => ["admin", "fixtures", query] as const,
  fixture: (id: string) => ["admin", "fixture", id] as const,
  odds: (matchId?: string) => ["admin", "odds", matchId ?? "trading"] as const,
  risk: ["admin", "risk"] as const,
  simulations: ["admin", "simulations"] as const,
  settlements: ["admin", "settlements"] as const,
  wallet: ["admin", "wallet"] as const,
  reports: (from: string, to: string) => ["admin", "reports", from, to] as const,
  audit: (query: object) => ["admin", "audit", query] as const,
  settings: ["admin", "settings"] as const,
  leagues: ["public", "leagues"] as const,
  standings: (leagueId: string) => ["public", "standings", leagueId] as const,
  liveMatches: ["public", "matches", "live"] as const,
};
