export const keys = {
  root: ["admin"] as const,
  list: (resource: string, query: object) => ["admin", "list", resource, query] as const,
  listTotal: (resource: string, filters: object) => ["admin", "list-total", resource, filters] as const,
  overview: ["admin", "overview"] as const,
  health: ["admin", "health"] as const,
  shop: (id: string) => ["admin", "shop", id] as const,
  shopDirectory: ["admin", "shop-directory"] as const,
  fixture: (id: string) => ["admin", "fixture", id] as const,
  odds: (matchId?: string) => ["admin", "odds", matchId ?? "trading"] as const,
  risk: ["admin", "risk", "overview"] as const,
  exposure: ["admin", "risk", "exposure"] as const,
  riskLimits: ["admin", "risk", "limits"] as const,
  analyticsOverview: (window: object) => ["admin", "analytics", "overview", window] as const,
  analyticsBreakdown: (query: object) => ["admin", "analytics", "breakdown", query] as const,
  analyticsSessions: (query: object) => ["admin", "analytics", "sessions", query] as const,
  accountAnalysis: (kind: string, id: string, window: object) => ["admin", "analytics", "account", kind, id, window] as const,
  operatorLedger: ["admin", "operator", "ledger"] as const,
  operatorPeriods: ["admin", "operator", "periods"] as const,
  commission: (periodId?: string) => ["admin", "commission", periodId ?? "current"] as const,
  commissionConfig: ["admin", "commission-config"] as const,
  wallet: ["admin", "wallet"] as const,
  reports: (from: string, to: string) => ["admin", "reports", from, to] as const,
  audit: (query: object) => ["admin", "audit", query] as const,
  settings: ["admin", "settings"] as const,
  leagues: ["public", "leagues"] as const,
  standings: (leagueId: string) => ["public", "standings", leagueId] as const,
  liveMatches: ["public", "matches", "live"] as const,
};
