export type {
  AccountRecord,
  CreditType,
  DebitType,
  EntryPage,
  EntryPageFilter,
  EntryRecord,
  EntrySortField,
  EntryTypeFilter,
  LedgerEntryType,
  OverviewRecord,
  OwnerType,
  PlatformEntryRecord,
  PostableEntryType,
  PostEntryInput,
  PostEntryResult,
  ShopEntryRecord,
  ShopEntryType,
  SortDirection,
  TimeRange,
  WalletRepository,
} from "./wallet.interface.js";
