export type {
  AccountRecord,
  CreditType,
  DebitType,
  EntryRecord,
  LedgerEntryType,
  OverviewRecord,
  OwnerType,
  PlatformEntryRecord,
  PostEntryInput,
  PostEntryResult,
  ShopEntryRecord,
  ShopEntryType,
  TimeRange,
  WalletRepository,
} from "./wallet.interface.js";
